apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-demo-ingress
  namespace: devsu-demo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - devsu-demo.solvextk.com
    secretName: devsu-demo-tls
  rules:
  - host: devsu-demo.solvextk.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsu-demo-service
            port:
              number: 80