apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-secrets
  namespace: devsu-demo
type: Opaque
data:
  DATABASE_USER: dXNlcg==  # base64 encoded "user"
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"